spring:
  mvc:
    throw-exception-if-no-handler-found: true
  data:
    mongodb:
      database: taxsubmission
      host: localhost
      port: 27017
security:
  basic:
    enabled: true
server:
  error: 
    whitelabel:
      enabled: false
